ICIJ/datashare

- datashare-api/src/main/java/org/icij/datashare/text/nlp/NlpApp.java
- datashare-api/src/test/java/org/icij/datashare/text/nlp/NlpAppTest.java
I noticed that `NlpAppTest`s often fail on my local checkout.
After some debugging I traced it down to a race condition in `NlpApp`/`NplConsumer`:
NlpApp shutdown waits for the queue to be drained and then sends a shutdown to the pool of `NplConsumer`s.
`NlpApp.shutdown()` only waits for a single millisecond in tests and if the pool is not shutdown issues a `shutdownNow()` which terminates all processing.
When NplConsumer drained the queue, but hasn't processed it yet - those in-flight operations are lost.
The tests rely on a strict definition of all data having been processed for the assertions to work (on the processing rate and with validating which methods were called). If NplConsumer doesn't have the time to finish its job - those assertions are invalid.
I preserved the default …
> Clean NlpApp shutdown in tests to avoid race conditions

- datashare-app/src/main/java/org/icij/datashare/tasks/IndexTask.java
A PR for https://github.com/ICIJ/datashare/issues/86. 
Not sure if this is what you had in mind, but happy to change it to something else.
This should reliably wait for termination and log if it's been interrupted in the process.
Alternatively this can be changed to simply `consumer.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);` which will have a similar effect of waiting forever.
I personally like this approach better because it provides a little more visibility into "actively" waiting for the shutdown.
> Wait for the consumer to be terminated

- datashare-cli/pom.xml
- datashare-cli/src/test/java/org/icij/datashare/cli/DatashareCliTest.java
This rule is no used since 8b0e061740702453ad232d7f892b133054a32a4c.
> Remove ExpectedSystemExit rule

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadLoop.java
- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadLoopTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerTest.java
Following [this commit](https://github.com/ICIJ/datashare/commit/6625d460b37ec84716138142ffc080421b5ee022) a bug has been introduced. 
After launching Datashare in Batch Download mode, this error message appears every minute : 
```
2023-01-12 16:18:31,419 [main] INFO  BatchDownloadLoop - Datashare running in batch mode. Waiting batch from ds:batchdownload.queue (class org.icij.datashare.extract.RedisBlockingQueue)
2023-01-12 16:19:31,531 [main] ERROR BatchDownloadLoop - error in loop
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
at …
```
> fix: batch download loop poll error

- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java
Related to #993 
The batchSearch without queries: 
before fix: based on a single project
after fix: get the BS projects from the BS and merge projects into a comma separated string of projects
The batchSearch with queries: not changed because they are already merging the projects into a comma separated string of projects with the "mergeBatchSearches". Eg with 2 projects (p1,p2) and 2 queries (q1, q2), the merge will create 4 rows p1q1, p1q2,p2q1, p2q2 and then retrieve all the different project values from these rows.
> fix: display project list in detailed view

- datashare-app/src/main/resources/extensions.json
- pom.xml
This PR aims to integrate libraries which are now updated to openjdk 11
- [Datashare-api](https://github.com/ICIJ/datashare-api/commit/2f4d5a1bb8e0adf758d9a238d68e34cdb4d715ed)
- [Open NLP](https://github.com/ICIJ/datashare-extension-nlp-opennlp/commit/fb39e94717fbcb45c26b69906f14ab66333831d0) and [here](https://github.com/ICIJ/datashare-extension-nlp-opennlp/commit/d00d56bf29537bc95f8410307e5bf20b3afe3540)
- [Mitie](https://github.com/ICIJ/datashare-extension-nlp-mitie/commit/0ffc721914a330ae27400743958314d248da3881)
- [Ixapipe](https://github.com/ICIJ/datashare-extension-nlp-ixapipe/commit/aa6a23557b06b619415dbe6509518963e87fb7da)
> build: upgrade extension json and pom

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadCleaner.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadCleanerTest.java
- pom.xml
This PR aims to adapt changes done in datashare-api. `BatchDownloadCleaner` now deletes archives with underscore and the ones double dots (generated with previous versions).
> feat: BDCleaner deletes archives with underscores

- datashare-db/pom.xml
- datashare-db/scr/reset_datashare_db.sh
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java
This PR aims at making it easier to develop Datashare locally.
I've manage to build DS and run some test by applying the following modifications.
- Bumped `sqlite-jdbc` to `3.40.1.0` in order to support MacOs Silicon
- Set test user password in `/scr/reset_datashare_db.sh` in order to avoid to type the password when `PGPASSWORD` is not set
- Import `import org.jooq.Record` unambiguously (compilation failed on my laptop due to ambiguity with `java.lang.Record`)
> chore: facilitate local development

- datashare-app/src/main/java/org/icij/datashare/web/UserResource.java
- datashare-app/src/test/java/org/icij/datashare/web/UserResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqRepositoryTest.java
- pom.xml
Rename user history methods to prevent confusion coming from https://github.com/ICIJ/datashare-api/commit/ceb7930c75293f4cd682cca5a9756372d9beee46
> Proposal to rename user history api methods

- datashare-app/src/main/java/org/icij/datashare/web/UserResource.java
- datashare-app/src/test/java/org/icij/datashare/web/UserResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqRepositoryTest.java
- pom.xml
Related to https://github.com/ICIJ/datashare/issues/1015
Add options to user history end point :
- sort: Sort on fields with  (keep modification_date as default). Wrong field raise a bad request http status
- desc: Choose sort order with desc (keep true by default)
- projects: filter by projects, passed as a list of projectIds (default all projects)
update on the api: [93c6b1f04f8ac9fa5a14a7017dbaf91ce51659a8](https://github.com/ICIJ/datashare-api/commit/93c6b1f04f8ac9fa5a14a7017dbaf91ce51659a8)
> Feat: user history sort filter

- datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java
- datashare-app/src/main/java/org/icij/datashare/web/IndexResource.java
- datashare-app/src/test/java/org/icij/datashare/web/DocumentResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/IndexResourceTest.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexer.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexerTest.java
- pom.xml
Sanitize parameters:
Restriction on index format (alpha/num/hyphen/dash)
Restriction on indices format (comma separated)
Prevent empty or null routingId or targetLangage on extracted text
> Fix: sanitize parameters

- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchConfiguration.java
- datashare-index/src/main/resources/datashare_index_settings_windows.json
On Windows, Elasticsearch doesn't manage paths properly. This PR aims to create an index with [settings](https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-pathhierarchy-tokenizer.html#_example_configuration_9) specially made for Windows
> feat: set up ES path tokenizer delimiter on windows

- datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java
- datashare-app/src/test/java/org/icij/datashare/web/DocumentResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/DatabaseSpewer.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/BenchDocument.java
- datashare-db/src/test/java/org/icij/datashare/db/DatabaseSpewerTest.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqRepositoryTest.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexer.java
- datashare-index/src/main/resources/extractedText.painless.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/DatashareExtractIntegrationTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexerTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractorTest.java
- pom.xml
This PR results from an update of the datashare api  (https://github.com/ICIJ/datashare-api/pull/11) about document, document builder and extracted text and is a mix of two refactors :
1/ Retrieve complete content and translation:
- Add API endpoint for retrieving complete text and translation on the extract text endpoint (@09622722aa6955c61bf1b0d2be3e244a837d8231)
2/ Document builder:
- Use document builder instead of document constructor to avoid endless list of constructor
- Update tests and code accordingly
Not fixed: 
Warning concerning Type reference in JSON serializer (Mapper readvalue) has not been changed to avoid a bigger refactor. 
This PR has been made with @bthomas. All commits will be squashed and merged to have a proper history.
> Refactor: use documentBuilder and add full extracted text content and translated content to API

- datashare-index/src/main/resources/datashare_index_settings.json
- datashare-index/src/main/resources/datashare_index_settings_windows.json
This PR use a different index settings to search into nested attributes of the content_translated field when doing a search without specifying the field.
Documentation about flattened field names: https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html
> fix: add missing nested fields for content_translated

- datashare-app/src/main/java/org/icij/datashare/Main.java
- datashare-dist/src/main/deb/bin/datashare
- launchBack.sh
Adding : 
A log to display JVM version.
And 
```
--add-opens java.base/java.lang=ALL-UNNAMED 
--add-opens java.base/java.util=ALL-UNNAMED
```
to `launchBack.sh` and datashare script for retro-compatibility from jdk17/18/19.
Tested with:
* 11 (to be sure that the option `--add-opens` doesn't break JDK11)
* OpenJDK 17 (LTS)
* OpenJDK 19 (latest available for ubuntu 22.02)
I didn't find any drawback of doing this, any ideas?
Same update to come in datashare-installer for snap.
> feat: JDK17 retro-compatibility

- datashare-index/src/main/resources/datashare_index_settings_windows.json
Elasticsearch settings file for windows wasn't edited as it should have been like in [this PR](https://github.com/ICIJ/datashare-client/pull/266/files#diff-32d99d68fd35ab2ae034ec7df1a435249136758969f03719acc295ef78f63f5a), causing an error at launch on Datashare on Windows
> feat: adds folding analyzer for windows

- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractor.java
This PR aims to give more context for extraction error that can often happen due to processing big files. Additionally to the document id of the failed document, we have now the project name and the routing id
> chore: adds project name and routing id on extraction error

- .circleci/config.yml
This PR to update the ci process.
In this issue, the release creation done with github API has been moved from the `deployed.sh` script that was in the datashare-installer repository into the circleci workflow to make it explicit.
> ci: change the release workflow #1089

- datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java
- datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java
This fix the isDownloadAllowed endpoint that was expecting a project in the database. It now works even when the project is not in the database.
> fix: ensure project isDownloadAllowed is correct

- datashare-app/src/main/resources/extensions.json
- datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java
- launchBack.sh
- pom.xml
This PR adds the support for the  [datashare-extension-neo4j](https://github.com/ICIJ/datashare-extension-neo4j) inside Datashare. It also provide some fixes needed to build datashare on a mac M1.
- Bumped logs dependencies to be aligned with the neo4j extension versions (needed to forward Python logs to the Datashare logger via `syslog`)
- Added to the [datashare-extension-neo4j](https://github.com/ICIJ/datashare-extension-neo4j) `0.1.1` tag to the `extension.json` repository
- Refacor `JooqRepository` imports to avoid ambiguous imports
- Avoid using `docker sudo` when using a darwin machine
> chore: add neo4j extension

- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/DbSetupRule.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java
- pom.xml
This PR adds a `maxResults` to the `GET` `/search/:batchid/queries` endpoint.
> feat: add a maxResults option to batch search queries endpoint

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerEncryptedIntTest.java
This PR reformats the email sent when a BatchDownload zip is password protected.
When Datashare is started with `rootUrl`, the email also contains a link:
If not, this line is not used:
> feat: add quotes arround password and more context info

- datashare-app/pom.xml
- datashare-app/src/main/java/org/icij/datashare/com/mail/MailSender.java
- datashare-app/src/test/java/org/icij/datashare/com/mail/MailSenderTest.java
Second PR to fix the use of mailsender with authenticated user.
It comes with  :
* fix for the logger that was not properly used
* a new parameter for TLS connection (on 465)
* a new debug parameter to see exactly why the mail sending is failing
* extracted a `shouldAuth()` méthod that centralize the criteria for knowing if we sould auth or not
> fix: use of TLS/auth for mail sender see #1106

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchSearchRunner.java
- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerIntTest.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/main/resources/liquibase/changelog/changes/032-batch-search-adds-tags-column.yml
- datashare-db/src/main/resources/liquibase/changelog/db.changelog.yml
- datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java
- pom.xml
Before:
Based on https://github.com/ICIJ/datashare/tree/feat/batch_search_tag_filter so
Add batch search result filter on contentTypes and allow querie filter inversion with queriesExcluded attribute.
Refactor: use WebqueryBuilder instead of Webquery construtor
> feat: add batchsearch results filters

- datashare-app/src/main/java/org/icij/datashare/mode/LocalMode.java
- datashare-app/src/main/java/org/icij/datashare/session/DatashareUser.java
- datashare-app/src/main/java/org/icij/datashare/session/LocalUserFilter.java
- datashare-app/src/main/java/org/icij/datashare/utils/IndexAccessVerifier.java
- datashare-app/src/main/java/org/icij/datashare/utils/PayloadFormatter.java
- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/main/java/org/icij/datashare/web/IndexResource.java
- datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java
- datashare-app/src/main/java/org/icij/datashare/web/RootResource.java
- datashare-app/src/test/java/org/icij/datashare/session/LocalUserFilterTest.java
- datashare-app/src/test/java/org/icij/datashare/session/YesCookieAuthFilterTest.java
- datashare-app/src/test/java/org/icij/datashare/utils/IndexAccessVerifierTest.java
- datashare-app/src/test/java/org/icij/datashare/utils/PayloadFormatterTest.java
- datashare-app/src/test/java/org/icij/datashare/web/ApiKeyResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/DocumentResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/ExtensionResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/IndexResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/NamedEntityResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/NoteResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/PluginResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/RootResourcePluginTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/WebLocalAcceptanceTest.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- pom.xml
This PR ensures that users are granted access to every projects in LOCAL mode.
* Upgrade to Datashare API 11.0.1 in order to use `user.setProjects` ;
* In LocalUserFilter, build a user with access to all projects ;
* Adapt all the test to mock `getProjects` from the `JooqRepository` ;
* Refactor `IndexResource` with `PayloadFormatter` utils class ;
* Add `IndexAccessVerifier` utils class.
> feat: allow multi projects in local

- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java
This tackles the issue of unknown BS returning a 500 as described in https://github.com/ICIJ/datashare/issues/1093.
The error handling is done at two level:
* In the `BatchSearchResources` to ensure the correct code and error message is shown
* In the `BatchSearchRepository` to ensure get a BS from the db is done with a safe accessor
> fix: unknown batch search wrong status

- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ResumeNlpTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/TaskFactory.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/tasks/ResumeNlpTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
This PR ensure that user can tweak the `defaultProject`, `queueName` and `reportName` when starting a new scanning, indexing and named entities finding. This will contribute to solve https://github.com/ICIJ/datashare/issues/1134.
* add a new constructor argument to `ResumeNlpTask` to receive runtime properties ;
* ensure request's body is used to populate properties on scanning/indexing endpoints ;
* add tests accordingly
> feat: project indexing

- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/main/java/org/icij/datashare/web/UserResource.java
- datashare-app/src/main/java/org/icij/datashare/web/WebResponse.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java
- pom.xml
Before : 
What is in this PR:
- Use webresponse format for filtered/paginated list of results (user history, batch search, batch search results) in the BREAKING CHANGE format:
```js
{
items:[..5items..],
pagination:{count: 5,from:0,size:5, total: 12}
}
```
Consequences:
Datashare client components about user history, batch search and batch search results should comply with new API response. 
Missing but not mandatory: return all available content types in a batch search
> feat: add pagination to filtered and paginated lists 

- datashare-app/src/main/resources/extensions.json
Bump extension version to `0.2.0` (skipping `0.1.2`)
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.0
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.1.2
> chore: bump neo4j extension to 0.2.0

- datashare-app/src/main/java/org/icij/datashare/Extension.java
- datashare-app/src/test/java/org/icij/datashare/ExtensionTest.java
- Fixed previous extension installation detection when extension name has digit
> fix: extension installation when digit in extension name

- datashare-app/src/main/resources/extensions.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.1
> chore: bump neo4j extension to 0.2.1

- datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java
- datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java
Add `DELETE` on the `/api/project/` endpoint so it can be used to delete all user's projects.
* add `DELETE` endpoint on `/api/project/`
* add doc for `GET` endpoint on `/api/project/`
* add preflight endpoint on `/api/project/` (for `GET`, `POST`, `OPTION` and `DELETE`)
> feat: delete all projects endpoint

- datashare-app/src/main/resources/extensions.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.2
> chore: bump neo4j extension to 0.2.2

- datashare-app/src/main/resources/extensions.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.3
> chore: bump neo4j extension to 0.2.3

- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewer.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
**Goal**
This PR is related to [this issue](https://github.com/ICIJ/datashare/issues/1173) and complete this [previous PR](https://github.com/ICIJ/datashare/pull/1174). This PR aims to use `dc_title` and `dc_subject` only for emails and tweets.
> fix: use title and subject for email/tweet #1173

- datashare-app/src/main/resources/extensions.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.5
> chore: bump `datashare-extension-neo4j` to `0.2.5`

- datashare-app/src/main/resources/extensions.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.6
> chore: bump `datashare-extension-neo4j` to `0.2.6`

- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- datashare-app/src/main/java/org/icij/datashare/Plugin.java
- datashare-app/src/main/java/org/icij/datashare/PluginService.java
- datashare-app/src/main/java/org/icij/datashare/web/RootResource.java
- datashare-app/src/test/java/org/icij/datashare/ExtensionServiceTest.java
- datashare-app/src/test/java/org/icij/datashare/PluginServiceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/ExtensionResourceTest.java
This PR adds the ability for `Plugin` to depend on a list of `Extension`.
The dependency was added on this direction because if a `Plugin` depends on an `Extension` the opposite it not always true and the extension might be usable standalone (even if a plugin can run on the top of it).
I also allowed a plugin to depend on several extensions (this is debatable but a bit more futureproof).
- added an optional `public final List<String> extensions`  to the `Plugin` class
- added a `private final ExtensionService extensionService;` to the `PluginService` which nows check if the installed plugin depends on extensions and installs them thanks to its `extensionService` if needed
> feature: support installation of plugins with extensions dependencies

- datashare-app/src/main/java/org/icij/datashare/tasks/IndexTask.java
- datashare-app/src/test/java/org/icij/datashare/tasks/IndexerHelper.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DigestAlgorithm.java
- datashare-cli/src/test/java/org/icij/datashare/cli/DatashareCliTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqApiKeyRepository.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewer.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/DatashareExtractIntegrationTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractorTest.java
- pom.xml
passing the options to extract.
The goal was  to simplify also between extract and datashare.
We use the options and we don't call the setter anymore.
> Feat: digest algorithm option

- commons-test/pom.xml
- datashare-index/pom.xml
- pom.xml
This is an attempt to detect I/O Reactor failure on ES client.
> chore: exclude httpcomponents from the ES java client

- datashare-dist/src/main/deb/control/control
This PR improves the deb package:
* to use `datashare` as package name (replacing `datashare-dist`)
* to use `ICIJ <datashare@icij.org>` in the maintainer field
* to depends on higher Java version
> build: use new name and bump Java version

- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewer.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
- pom.xml
this PR is made to generalize the `digestAlgorithm` cli option to Duplicate type hash generation.
Note that with duplicates, for now, the project is never encoded in the hash.
> feat: hash duplicates with cli option digestAlgorithm

- datashare-app/src/main/java/org/icij/datashare/nlp/EmailPipeline.java
- datashare-app/src/test/java/org/icij/datashare/nlp/EmailPipelineTest.java
- datashare-index/src/main/resources/datashare_index_mappings.json
- datashare-index/src/main/resources/datashare_index_settings.json
Updated the `EmailPipeline` to preserve email header metadata when parsing emails. 
If the header contains `email2@domain.com,email3@domain.com` as `CC`, the parser will create 2 named entities with `{"emailHeaderField": "tika_metadata_message_cc"}` metadata.
**Please carefully review the naming** of the metadata as field as it will be painful the change it later, I'm open to suggestions.
- modified `EmailPipeline.process` to preserver email header field name and use it as `NamedEntity.metadata` under the `emailHeaderField` key
- included the `NamedEntity.metadata.emailHeaderField` in the indexed fields as a `keyword`
- included the `NamedEntity.metadata.emailHeaderField` in the `index.query.default_field` 
- bumped `datashare-api` to `11.3.2` to add support for `NamedEntity.metadata`
> feature: include email header type in EMAIL name entity metadata

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractor.java
When downloading an embedded document, Datashare tries to get it with several digesters instead of one.
> feat: use several digesters to found embedded doc

- .circleci/config.yml
- .circleci/maven-release-settings.xml
- .gitignore
- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- datashare-app/src/main/java/org/icij/datashare/ExtensionService.java
- datashare-cli/pom.xml
- datashare-cli/src/main/java/org/icij/datashare/cli/CliExtensionService.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
- datashare-cli/src/main/java/org/icij/datashare/cli/spi/CliExtension.java
- datashare-cli/src/test/java/org/icij/datashare/cli/CliExtensionFoo.java
- datashare-cli/src/test/java/org/icij/datashare/cli/CliExtensionServiceTest.java
- datashare-cli/src/test/java/org/icij/datashare/cli/DatashareCliTest.java
- datashare-cli/src/test/resources/META-INF/services/org.icij.datashare.cli.spi.CliExtension
The goal of this request is to add a simple command line interface extension mechanism. It works not on the same way as others extensions because others extensions needed an extension folder that is set... in the CLI. So there was a chicken-and-egg issue.
So we used instead the [Service Provider](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html) way.
Extensions that intend to update the command line interface and properties should:
1. add the `datashare-cli-<version>.jar` in their dependencies (see the maven [jar page](https://central.sonatype.com/artifact/org.icij.datashare/datashare-cli))
2. implement the Service Provider Interface `CliExtension` (SPI)
3. add a `src/java/resources/META-INF/services/org.icij.datashare.cli.spi.CliExtension` text file with the list of …
> feat: add cli extension

- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- launchBack.sh
see ICIJ/datashare-extension-neo4j#80
The goal of the PR is to update the launchBack.sh script and add a log to debug easily the CLI extension loading.
The `launchBack.sh` script can be called with a cli extension like this:
```
CLASSPATH=./datashare-dist/target/datashare-dist-13.2.6-docker/lib/datashare-dist-13.2.6-all.jar:../cli-ext/target/cli-ext-1.0-SNAPSHOT.jar ./launchBack.sh -m CLI --ext foo
```
> fix: CLI extension add log and updates launchBack script 

- datashare-dist/src/main/docker/entrypoint.sh
When using CLI extensions (#1207), it will be necessary to start `datashare` with an extended classpath pointing to the CLI extension jars. This PR allows to extend the docker image `CLASSPATH` rather than (re)-setting it in the `datashare`'s docker entrypoint.
- extend the image environment `CLASSPATH` with datashare's class path when calling docker entry point
> chore: allow extending env `CLASSPATH` in docker image

- datashare-cli/pom.xml
- datashare-cli/src/main/java/org/icij/datashare/cli/CliExtensionService.java
- datashare-cli/src/main/java/org/icij/datashare/cli/spi/CliExtension.java
- datashare-cli/src/test/java/org/icij/datashare/cli/CliExtensionFoo.java
- datashare-cli/src/test/java/org/icij/datashare/cli/CliExtensionServiceTest.java
- datashare-cli/src/test/java/org/icij/datashare/cli/FooService.java
Completes the work done in #1207 to allow to extend Datashare CLI with `CliExtension` which have dependencies.
Previously the extension mechanism required the `CliExtension` to have a [zero-arg constructor](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) which was very limiting as most CLI extension will need to use dependency injection
This PR leverages a factory-like pattern to allow extending the CLI with extensions relying on dependency injection.
Replaces and closes #1231
> feature: support dependency injection in CliExtension

- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/test/java/org/icij/datashare/cli/DatashareCliTest.java
In the previous implementation the `DatashareCli` was not including the main DS CLI options in the extended CLI  preventing to call the extension as following:
```bash
datashare -m CLI -s mySetting.properties --extensionsDir ./extensionPath  --ext neo4j --full-import -p myProject
```
The parsing of all configuration arguments of the CLI would have to be re-implemented in each extension. This change the extension mechanism to leave configuration arguments in the extended CLI, while not printing them when the help is called.
- refactored `DatashareCli.parseArguments` to include DS configuration arguments while not printing then when the extension help is called
> fix: extension cli to support main datashare CLI options

- .circleci/config.yml
- datashare-cli/pom.xml
- datashare-db/pom.xml
- datashare-db/scr/reset_datashare_db.sh
This PR replace shade plugin when it is not needed.
And it uses another database for code generation than datashare to avoid conflicting issues when testing locally and building.
> refactor: build improvements

- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
Related to  #1240
Use GET HTTP verb instead of POST to have 304 not modified HTTP status when query/response are identical (eTag) 
This is particularly important during polling to prevent response to be downloaded for each (unchanged) query (previous behavior returned 200 OK with same response each time)
> refactor: cache batch search list

- datashare-cli/pom.xml
- pom.xml
release new version of datashare-cli 
That should be made in the main pom.xml for the project version and in the datashare-cli module.
> fix: release datashare-cli 13.5.0

- commons-test/pom.xml
- commons-test/src/main/java/org/icij/datashare/test/ElasticsearchRule.java
- datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java
- datashare-app/src/main/java/org/icij/datashare/web/IndexWaiterFilter.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerEncryptedIntTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerIntTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerIntTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/IndexerHelper.java
- datashare-app/src/test/java/org/icij/datashare/tasks/ResumeNlpTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/ScanIndexTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/web/IndexResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/IndexWaiterFilterTest.java
- datashare-index/pom.xml
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchConfiguration.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexer.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSearcher.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewer.java
- datashare-index/src/main/java/org/icij/datashare/utils/JsonUtils.java
- datashare-index/src/main/resources/datashare_index_settings.json
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/DatashareExtractIntegrationTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchConfigurationTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexerTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/EsEmbeddedServerIntTest.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractorTest.java
- datashare-index/src/test/java/org/icij/datashare/utils/JsonUtilsTest.java
- pom.xml
This PR aims to replace [current HLRC](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.10/java-rest-high-getting-started.html) by [Java API](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/7.17/_getting_started.html)
> refactor: use JAVA api

- datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java
- datashare-app/src/test/java/org/icij/datashare/web/DocumentResourceTest.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractor.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractorTest.java
- pom.xml
when extracting source from a file, we can't know if the file is not found or the content is not found.
Besides there is no logs, we can't know what is going on.
> fix: log when embedded content is not found

- datashare-app/src/main/java/org/icij/datashare/Plugin.java
- datashare-app/src/test/java/org/icij/datashare/PluginServiceTest.java
Previous installation removal was failing whenever a file in the `pluginsDir` was matching a plugin pattern.
The remove code was bug and was returning both plugin directories and plugin files with a plugin pattern.
When deleting the file a exception was thrown since we were attempting `FileUtils.deleteDirectory(file)` on files and not directories
- fixed the remove of previous plugin installation to attempt to remove only directories matching the plugin pattern inside the `pluginsDir`
> fix: previous plugin installation

- datashare-app/src/main/resources/extensions.json
- datashare-app/src/main/resources/plugins.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.1
> chore: bump neo4j extension and plugin to `0.3.1`

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadLoop.java
- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java
- datashare-app/src/main/java/org/icij/datashare/tasks/FileResult.java
- datashare-app/src/main/java/org/icij/datashare/tasks/TaskFactory.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerIntTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserTaskResourceTest.java
- pom.xml
This PR to avoid side effect on BatchDownload object (removed the `setSize` method in `datashare-api`).
Instead, the size of the zip is returned to front by the result of the task.
> fix: returns a FileResult with size/path #1081

- datashare-app/src/main/resources/extensions.json
- datashare-app/src/main/resources/plugins.json
Bump from [`0.3.2` to `0.3.6`](https://github.com/ICIJ/datashare-extension-neo4j/compare/0.3.2...0.3.6):
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.2
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.3
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.4
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.5
- https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.6
> chore: bump neo4j extension and plugin to `0.3.6`

- datashare-app/src/main/resources/extensions.json
- datashare-app/src/main/resources/plugins.json
- launchBack.sh
- bump the neo4j extension to [0.3.12](https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.12)
- reverted change committed by error in `launchBack.sh`
> chore: bump neo4j to `0.3.12`

- datashare-app/src/main/java/org/icij/datashare/WebApp.java
- datashare-app/src/main/java/org/icij/datashare/com/bus/amqp/QpidAmqpServer.java
- datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java
- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadCleaner.java
Adds the start of AMQP [Qpid](https://qpid.apache.org) broker in local mode to interact with tasks written in other languages via AMQP.
It will be started if:
* it is in embedded mode
* there is an AMQP queue in options
Plus a small fix on BatchDownloadCleaner when the batch download dir doesn't exist.
> Feat: AMQP embedded Qpid

- datashare-app/src/main/resources/extensions.json
- datashare-app/src/main/resources/plugins.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.3.13
> chore: bump neo4j extension and plugin to `0.3.13`

- datashare-app/src/main/resources/extensions.json
- datashare-app/src/main/resources/plugins.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.4.0
> chore: bump neo4j extension and plugin to `0.4.0`

- datashare-app/src/main/resources/extensions.json
- datashare-app/src/main/resources/plugins.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.4.2
> chore: bump neo4j extension and plugin to `0.4.2`

- datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java
- datashare-app/src/main/java/org/icij/datashare/web/RootResource.java
- datashare-app/src/test/java/org/icij/datashare/mode/CommonModeWebExtensionTest.java
- datashare-app/src/test/java/org/icij/datashare/web/RootResourcePluginTest.java
This PR ensures that invalid plugins and extensions dirs won't crash the application (#1329).
* feat: check for plugins dir existence before loading it in `RootResource`
* feat: check for extensions dir existence before loading it in `RootResource`
* feat: check for plugins dir existence before adding to the CommonMode routes
* refactor: show warnings at startup when using invalid plugins and extensions dirs
> feat: optional plugins and extensions dirs

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchSearchRunner.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerIntTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java
Related to [this issue](https://github.com/ICIJ/datashare/issues/1322)
This PR implements : 
- Fix the saving function for the Batch Search into the DB, the query template field couldn't be saved as a null value
- Without the previous fix it was impossible for the runner to do the search properly
The last thing to do is to migrate the `query_template` field by replacing empty values ("") by null values
> fix: batch search relaunch

- datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
While debugging #1333 we discovered the queues are not correctly deleted when deleting a project. To avoid this issue from happening again, this PR adds more constraints to the queues created in LOCAL (from the client).
* feat: scan and index endpoint constraint the queueName based on the project name 
* feat: project deletion endpoint deletes queues from every stage
* refactor: find queues to delete using the PipelineHelper class
> feat: ensure consistancy when creating/deleting queues in LOCAL mode

- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- datashare-app/src/main/java/org/icij/datashare/tasks/DeduplicateTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ExtractNlpTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/IndexTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/PipelineTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ScanIndexTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ScanTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/TaskFactory.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/tasks/DeduplicateTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/ScanIndexTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
Ensure the project is used when creating a report map (as part of the ScanIndex task). See https://github.com/ICIJ/datashare/issues/1344.
> fix: scan index task project

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java
- datashare-app/src/main/java/org/icij/datashare/tasks/BatchSearchRunner.java
- datashare-app/src/main/java/org/icij/datashare/tasks/EnqueueFromIndexTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ExtractNlpTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/IndexTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ScanIndexTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerMemory.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerIntTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerIntTest.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
Related to [this issue](https://github.com/ICIJ/datashare/issues/1270)
This PR aims to add the scroll size option for Batch Search/Download and EnqueueTask.
It also define more default constants values options.
Scroll slice option for the other tasks can be issued in another story as the implementation is very specific for each tasks (we can also dig into the using of elasticsearch's [PIT](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/point-in-time-api.html#point-in-time-keep-alive)
> feat: adds scrollSize for batch and enqueue tasks

- datashare-dist/pom.xml
- datashare-dist/src/main/deb/bin/datashare
- datashare-dist/src/main/docker/entrypoint.sh
- pom.xml
this PR allows to run datashare with : 
```shell
java -jar datashare-dist/target/datashare-dist-15.1.2-all.jar
```
Or with 
```shell
java --add-opens java.base/java.lang=ALL-UNNAMED -cp datashare-dist/target/datashare-dist-15.1.2-all.jar org.icij.datashare.Main
```
> fix: move --add-opens from command line to MANIFEST.MF #1367

- datashare-app/src/main/java/org/icij/datashare/mode/ServerMode.java
- datashare-app/src/main/java/org/icij/datashare/session/ALBCognitoOAuth2CookieFilter.java
This pull request introduces several enhancements to authentication handling, specifically for projects integrating with AWS ALB and Cognito. It provides greater flexibility through custom classes and supports a new authentication scenario. 
- **Custom Classes for authUsersProvider & authFilter**: These classes allow for more nuanced customisation of the authentication process, accommodating unique business requirements not previously covered. We ensure that we are using the system's class loader so that custom classes (even those via extensions for example) can be loaded by the Datashare application.
- **New Auth Filter Class for AWS ALB + Cognito**: This new filter supports scenarios where AWS ALB is used in conjunction with Cognito to manage authentication, providing a streamlined …
> feat: custom classes for authUsersProvider & authFilter + new auth filter class for AWS ALB + Cognito

- launchBack.sh
- set `DATASHARE_HOME` in `./launckBack` to launch dev jar
> fix: set DATASHARE_HOME in `./launckBack` to launch dev jar

- .circleci/config.yml
- datashare-api/pom.xml
- datashare-api/src/main/java/org/icij/datashare/Repository.java
- datashare-db/pom.xml
- datashare-db/src/main/java/org/icij/datashare/db/JooqApiKeyRepository.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java
- datashare-db/src/main/java/org/icij/datashare/db/RepositoryFactoryImpl.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqRepositoryTest.java
- datashare-dist/src/main/deb/control/control
- pom.xml
The reason of this PR is [this issue](https://github.com/ICIJ/datashare/issues/1411) where the user history wasn't deleted properly. One of the solution was to use a `RETURNING` clause in SQL to delete entries in `USER_HISTORY_PROJECT` and `USER_HISTORY`. This clause is not implemented for SQLite in Jooq 3.12.3 so an update was needed.
One of the important changes is the [removal](https://github.com/jOOQ/jOOQ/issues/10512) of `AutoClosable` from `DSLContext` and the use of `ClosableDSLContext` instead. ([related commit](https://github.com/ICIJ/datashare/commit/b6e94381eabb62674dbbb67e9da0d82305084e06))
The other change is the use of `LocalDateTime` format by Jooq functions instead of `Timestamp` ([related commit](https://github.com/ICIJ/datashare/commit/b6e94381eabb62674dbbb67e9da0d8230508 …
> build: bump/jooq 3.12.3 to 3.19.10

- datashare-api/src/main/java/org/icij/datashare/json/JsonObjectMapper.java
- datashare-api/src/test/java/org/icij/datashare/json/JsonObjectMapperTest.java
Related to [this issue](https://github.com/ICIJ/datashare/issues/1426)
This PR aims to set up a max string length for Jackson other than the default 20MB value.
It is done by setting up the `streamReadConstraints` at the creation of the `ObjectMapper`
We set up these parameters : 
- `maxNestingDepth` : 20 (originally 1000)
- `maxNumLength` : 100 (originally 1000)
- `maxStringLength`: [1GB](https://github.com/ICIJ/datashare/blob/6107c1a2ddf4ec99d080a8157e94b8627ae18e3c/datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java#L61) (originally 2MB)
> feat: add streamReadConstraints for the objectmapper

- datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java
- datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
- datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractor.java
- datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/SourceExtractorTest.java
- pom.xml
See #1165 for the list of commits. Changes are made in extract-lib. https://github.com/ICIJ/extract/commit/f09254eb0d05c54c8df657acf73641d3193e2f5b
If null is provided in the [EmbeddedDocumentExtractor](https://github.com/ICIJ/extract/blob/7ed996daa13e211bb2df488f712b2b46d30473a8/extract-lib/src/main/java/org/icij/extract/extractor/EmbeddedDocumentExtractor.java) as the `artifactPath` then memory is used, else the provided path will be used as file cache for embedded files.
> feat: embedded artifacts

- .circleci/config.yml
This ensure the new design is bundled with the front end when releasing a new version of Datashare.
> build: add new design in a "next" subfolder

- datashare-api/src/main/java/org/icij/datashare/user/User.java
- datashare-api/src/test/java/org/icij/datashare/user/UserTest.java
- datashare-app/src/main/java/org/icij/datashare/session/OAuth2CookieFilter.java
- datashare-app/src/main/java/org/icij/datashare/session/OAuth2CookieFilterIcij.java
- datashare-app/src/main/java/org/icij/datashare/session/YesCookieAuthFilter.java
- datashare-app/src/test/java/org/icij/datashare/session/YesCookieAuthFilterTest.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
- datashare-cli/src/test/java/org/icij/datashare/cli/DatashareCliTest.java
This PR isolate ICIJ settings in a new class.
And adds a `--oauthUserProjectsAttribute` option to be able to specify a custom JSON attribute path (dot separated).
see #1585
> Feat: oauth2 parametrize ICIJ identity provider specific values

- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerMemory.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskManagerMemoryForBatchSearchTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskWorkerLoopForPipelineTasksTest.java
- datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserTaskResourceTest.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerMemory.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerMemoryTest.java
when we refactored the task management system we changed `CliApp` class to execute sequentially the tasks.
To distribute tasks like INDEX,ARTIFACT it could be better to execute these tasks in parallel.
> feat: parallelize cli with multithreaded task manager

- datashare-app/src/main/java/org/icij/datashare/CliApp.java
- datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java
- datashare-app/src/main/java/org/icij/datashare/tasks/ArtifactTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/EnqueueFromIndexTask.java
- datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerRedis.java
- datashare-app/src/test/java/org/icij/datashare/mode/CliModeWorkerAcceptanceTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/ArtifactTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/EnqueueFromIndexTaskTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskManagerMemoryForBatchSearchTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskWorkerLoopForPipelineTasksTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskWorkerLoopIntTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserTaskResourceTest.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java
- datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
- datashare-index/src/main/java/org/icij/datashare/extract/MemoryDocumentCollectionFactory.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/Task.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManager.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerAmqp.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerMemory.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerRedis.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerMemoryTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerRedisTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagersIntTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TestFactory.java
This PR fixes several issues:
- task CLI should handle the task `GROUP`
- missing singleton annotations that created several instances of services
- the waitForTasks that used an object instance lock with network access. It doesn't work because instance lock is changing at each network retrieval
- split of `shutdownAndAwaitTermination(timeout)` in two methods `shutdown()` and `awaitTermination(timeout)` 
see #1598
> Fix: workers shutdown cli

- datashare-app/src/main/java/org/icij/datashare/DeliverableHelper.java
- datashare-app/src/main/java/org/icij/datashare/Extension.java
- datashare-app/src/main/java/org/icij/datashare/OsArchDetector.java
- datashare-app/src/main/java/org/icij/datashare/Plugin.java
- datashare-app/src/test/java/org/icij/datashare/DeliverableHelperTest.java
- datashare-app/src/test/java/org/icij/datashare/ExtensionServiceTest.java
- datashare-app/src/test/java/org/icij/datashare/ExtensionTest.java
- datashare-app/src/test/java/org/icij/datashare/OsDetectorTest.java
- datashare-app/src/test/java/org/icij/datashare/PluginServiceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/ExtensionResourceTest.java
In order to download and execute the binary running the Spacy worker (https://github.com/ICIJ/datashare/issues/1452 ), we need the extension mechanism to be able to support installing non-jar binary executable.
This PR extends the `Extension` to support any type of extension with the following convention:
- URLs with an extension (`.jar` or others) are expected to be non platform specific
- URLs with non extension are expected to be platform specific (and thus download a platform specific binary given the extension name)
The convention could be changed to be more explicit however this will probably imply updating the data model of the `Extension` in a breaking manner (might not be an issue).
- added support to extend Datashare with any kind of binary extension
> feature: support arbitrary extensions

- datashare-app/src/main/java/org/icij/datashare/web/ApiKeyResource.java
- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/main/java/org/icij/datashare/web/ExtensionResource.java
- datashare-app/src/main/java/org/icij/datashare/web/IndexResource.java
- datashare-app/src/main/java/org/icij/datashare/web/NerResource.java
- datashare-app/src/main/java/org/icij/datashare/web/NoteResource.java
- datashare-app/src/main/java/org/icij/datashare/web/PluginResource.java
- datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java
- datashare-app/src/main/java/org/icij/datashare/web/RootResource.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/main/java/org/icij/datashare/web/TreeResource.java
- datashare-app/src/main/java/org/icij/datashare/web/UserResource.java
html was not interpreted by gitbook openapi translation.
So we used markdown:
- for code the triple backquotes are working fine
- for the line breaks you can use `\n\n` (note that a single `\n` will be ignored like in markdown and more `\n` are ignored also)
> Fix: openapi html to md documentation

- datashare-app/src/main/java/org/icij/datashare/web/OpenApiResource.java
- datashare-app/src/test/java/org/icij/datashare/web/OpenApiResourceTest.java
We thought that it would help to use html description texts in the openapi documentation but it didn't :(
As the impact is not that important in the code, we could keep the changes.
what do you think?
> feat: allows to return OpenAPI yaml format

- datashare-api/pom.xml
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerAmqp.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/AmqpChannel.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/AmqpInterlocutor.java
- pom.xml
refactor: code duplication for queue creation
fix 500 error. `GetHealth()` returns result of a monitoring event publication if monitoring is set to true. Else it returns if the AMQP connection is open.
see #1638
> Fix: monitoring event

- datashare-app/src/main/java/org/icij/datashare/ExecutableExtensionHelper.java
- datashare-app/src/main/java/org/icij/datashare/WebApp.java
- datashare-app/src/main/java/org/icij/datashare/mode/EmbeddedMode.java
- datashare-app/src/main/java/org/icij/datashare/mode/LocalMode.java
- datashare-app/src/main/java/org/icij/datashare/nlp/PythonNlpWorkerPool.java
- datashare-app/src/main/java/org/icij/datashare/utils/ProcessHandler.java
- datashare-app/src/main/resources/extensions.json
- datashare-app/src/test/java/org/icij/datashare/nlp/PythonNlpWorkerPoolTest.java
- datashare-app/src/test/java/org/icij/datashare/utils/ProcessHandlerTest.java
- datashare-app/src/test/resources/extensions/datashare-extension-nlp-spacy-0.9.0
Following #1611 and to address #1452
This PR adds the ability to start worker pool of NLP Python workers when in `EMBEDDED` mode with `AMQP` support/bus type.
- added a `ExecutableExtensionHelper` in charge of executing DS executable extension (non JAR)
- created a `ProcessHandler` to cleanly handle external processes (dump pids, find running process of some type, kill process etc)
- updated `WebApp` to spawn NLP workers when in `EMBEDDED` mode with `AMQP`, if such process are already running the application will ask the user to clean the phantom process (could be otherwise)
> feature: start python NLP workers in embedded mode

- datashare-app/src/main/java/org/icij/datashare/DeliverableHelper.java
- datashare-app/src/test/java/org/icij/datashare/DeliverableHelperTest.java
- fix `DeliverableHelper.hostSpecificUrl` when version appears twice in the deliverable URL
> fix: host specific url 

- .circleci/config.yml
For the next few weeks and until v20, we enter a transitional phase where both the legacy and new frontend will be shipped together with Datashare. The next design is now available from the `/next` but it's build directly from the [main branch](https://github.com/ICIJ/datashare-client/tree/main/).
This PR modifies the build workflow to download the legacy frontend from a past release (namely 19.8.10), extract it in the `/tmp/datashare/app` and use it by default:
```yml
- run:
name: download the legacy front from a past release
command: |
mkdir -p /tmp/datashare/app
curl -sL https://github.com/ICIJ/datashare-client/releases/download/19.8.10/datashare-client-19.8.10.tgz | tar xvz -C /tmp/datashare/app
- run:
name: make app link to front from a "next" subfolder
command: 
rm -Rf …
```
> build: temporary legacy mode

- datashare-api/src/test/java/org/icij/datashare/batch/BatchSearchRecordTest.java
- datashare-app/src/main/java/org/icij/datashare/tasks/BatchSearchRunner.java
- datashare-app/src/main/java/org/icij/datashare/tasks/DatashareTaskFactory.java
- datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserTaskResourceTest.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/Task.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManager.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/Event.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerMemoryTest.java
This PR add retro-compatibility for listing batch searches without tasks (#1794). To address this problem, the backend create on the fly "BatchSearchRunnerProxy" tasks that are merged with the actual list of tasks.
This also has the benefit to add access control to the batch searches tasks belonging to other user in server mode. Because the list of tasks is built based on the batch searches a user has access to, this create a way for them to see tasks they did not authored.
The frontend was already modified to support this new type of task.
> feat: batch searches proxy

- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManager.java
In order to add proper pagination to the task pages (see #1798), we need to know the total number of tasks. This PR adds a new `/api/task` endpoint with pagination metadata, for instance:
```json
{
"pagination": {
"count": 3,
"from": 0,
"size": 3,
"total": 5
},
"items": [
{
"id": "653de5ef-c245-4126-8ce3-8307f360b07d",
"name": "org.icij.datashare.tasks.IndexTask",
"state": "RUNNING",
"progress": 0.0,
"createdAt": "2025-04-25T16:59:34.368+00:00",
"retriesLeft": 3,
"args": { }
},
{
"id": "b5aa4678-3d2b-4c67-892f-ba43b6847df3",
"name": "org.icij.datashare.tasks.IndexTask",
"state": "DONE",
"progress": 1.0,
"createdAt": "2025-04-25T17:00:46.578+00:00",
"retriesLeft": 3,
"completedAt": "2025-04-25T17:00:51.882+00:00",
"args": {}
},
{
"id": "365f8cc3-560a-4865-856d-232063fde603",
"name": …
```
> feat: add `/api/task` endpoint with pagination

- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
Add the ability to have multiple values in filters like task names: "/api/task?name=scan|index"
> fix: add arbitrary filter with multiple values separated by a pipe on tasks

- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/tasks/CreateNlpBatchesFromIndexParametrizedTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/CreateNlpBatchesFromIndexTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskManagerMemoryForBatchSearchTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskWorkerLoopForPipelineTasksTest.java
- datashare-app/src/test/java/org/icij/datashare/tasks/TaskWorkerLoopIntTest.java
- datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceBatchSearchTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-tasks/pom.xml
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManager.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerAmqp.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerMemory.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerRedis.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerAmqpTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerMemoryTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerRedisTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagersIntTest.java
- pom.xml
Currently each time we filter tasks we always materialize them in a list which contains all tasks. As we run more tasks to Datashare this list can grow very large, using a stream API will help reduce the memory footprint of task search.
- change `TaskManager` APIs to return task streams
> chore: refactor task manager to return stream of tasks

- datashare-api/pom.xml
- datashare-api/src/main/java/org/icij/datashare/batch/WebQueryPagination.java
- datashare-api/src/main/java/org/icij/datashare/user/User.java
- datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java
- datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java
- datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceBatchSearchTest.java
- datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java
- datashare-app/src/test/java/org/icij/datashare/web/UserTaskResourceTest.java
- datashare-db/src/main/java/org/icij/datashare/db/JooqTaskRepository.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqTaskRepositoryTest.java
- datashare-tasks/pom.xml
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/Task.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskFilters.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManager.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerAmqp.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerMemory.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerRedis.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRepository.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRepositoryMemory.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRepositoryRedis.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskFilterTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerAmqpTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerMemoryTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerRedisTest.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagersIntTest.java
- pom.xml
Fixes #1803 (as a side effect of the refactoring)
Currently the task search APIs support arbitrary filters which in practice are not used arbitrarily.
The frontend only searches by:
- user ID
- arg value
- task name
On the other hand, supporting arbitrary filters negatively impacts task search, indeed to perform this arbitrary search we:
1. fecth **all task records** from the DB
2. convert them to JSON strings
3. apply the filter on the JSON string
This approach won't scale to many task records.
In contrast, this PR refactors the current task search API, unifies it using a common `TaskManager.getTask(TaskFilters filters)` API supporting all current task searchs (+ searching by task state).
In addition, the `TaskManager.getTask(TaskFilters filters)` API is implemented in each underlying …
> chore: unify and optimize task search APIs (`TaskManager.getTasks`)

- datashare-db/src/main/java/org/icij/datashare/db/ExtendedHikariDatasource.java
- datashare-db/src/main/java/org/icij/datashare/db/RepositoryFactoryImpl.java
- datashare-db/src/test/java/org/icij/datashare/db/JooqTaskRepositoryTest.java
- missing `REGEX` SQL function for SQLite DB connection
> fix(datashare-db): Sqlite regex search for JooqTaskRepositoryTest

- datashare-api/src/main/java/org/icij/datashare/test/LogbackAppenderWrapper.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/AmqpChannel.java
- datashare-tasks/src/test/java/org/icij/datashare/asynctasks/bus/amqp/AmqpTest.java
This PR fixes a bug where all exception (except from `NackException` and `Deserializer.DeserializeException`) were not acking or nacking messages, leaving the consumer unavailable for subsequent messages.
This PR modifies this behavior by requeing all unhandled exceptions, which means that **developers will have to explicitly throw `NackException(requeue=false)` on codeblocks where they expect errors to end up in a non requeud message**.
This is a debatable choice, but it seems more reasonable than no requeing by default which could end up in losing important information (unless we explicitely care about throwing NackException(requeue=true).
- fixed a bug where all unhandled  exceptions (except from `NackException` and `Deserializer.DeserializeException`) leave the channel consumer …
> fix(asynctasks): AMQP exception handling

- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/AmqpChannel.java
- datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/AmqpQueue.java
While #1878 improved exception handling, error handling by requeing message when unhandled exception occurred, it contributed to congest the event queue as event message had no delivery limit, hence the same message ended up being requeued over and over.
While setting delivery limit for even queue would be the ideal solution, this would imply using quorum queues for events. Migrating from classical queues to quorum queues is tricky as it requires to delete the queue and recreate it with a different type. To avoid such migration, we just don't requeue messages in case of unhandled exception.
Additionally workers were not expiring their event queue when dying which resulted in a lot of unused hanging queues
- ~set delivery limits on all event message queues~ -> don't requeue message in case …
> fix(datashare-asynctasks): don't requeue message when unhandled exception occur and set worker event queues expiration
