README.md
=> Update README.me, docker command explanation

datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadLoop.java, datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java, datashare-app/src/test/java/org/icij/datashare/mode/CliModeTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadLoopIntTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadLoopTest.java, datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java
=> feat: make batch download folder configurable

datashare-app/src/main/java/org/icij/datashare/com/mail/MailSender.java, datashare-app/src/test/java/org/icij/datashare/com/mail/MailSenderTest.java
=> feat: add user/pass support for MailSender  #1106

datashare-app/pom.xml, datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java, datashare-app/src/main/java/org/icij/datashare/web/ApiKeyResource.java, datashare-app/src/main/java/org/icij/datashare/web/OpenApiResource.java, datashare-app/src/test/java/org/icij/datashare/web/OpenApiResourceTest.java
This PR is adding an openapi endpoint that returns the specification file in json.
=> feat: swagger openapi

datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java, datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java, datashare-app/src/main/java/org/icij/datashare/web/IndexResource.java, datashare-app/src/main/java/org/icij/datashare/web/NamedEntityResource.java, datashare-app/src/main/java/org/icij/datashare/web/NerResource.java, datashare-app/src/main/java/org/icij/datashare/web/NoteResource.java, datashare-app/src/main/java/org/icij/datashare/web/PluginResource.java, datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java, datashare-app/src/main/java/org/icij/datashare/web/RootResource.java, datashare-app/src/main/java/org/icij/datashare/web/StatusResource.java, datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java, datashare-app/src/main/java/org/icij/datashare/web/TreeResource.java, datashare-app/src/main/java/org/icij/datashare/web/UserResource.java
PR for open API documentation migration with @mvanzalu 
Not perfect : there are still some generation issues (for example parts of annotations that are not exported), but the syntax is correct, and we can improve it later to avoid this long lasting branch to live longer.
=> Refactor: openapi migration

datashare-app/pom.xml, datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java, datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java, datashare-app/src/main/java/org/icij/datashare/web/NoteResource.java
this PR fixes some missed issues about openapi documentation : 
- forgotten parameter declarations
- double parameter generation (upgrade the fluent-swagger library)
- body request parameter declaration
=> Fix: openAPI display issues

datashare-app/pom.xml, datashare-app/src/main/java/org/icij/datashare/web/RootResource.java
This PR to fix import from services (gitbook, redoc...).
=> fix: remove '/' doc add info/version into the root resource

datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java, datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java, pom.xml
This PR ensure a project's queue and report map are deleted when deleting a project (https://github.com/ICIJ/datashare/issues/1145).
=> feat: project delete report map

datashare-app/src/main/java/org/icij/datashare/mode/ServerMode.java, datashare-app/src/main/java/org/icij/datashare/session/YesCookieAuthFilter.java, datashare-app/src/test/java/org/icij/datashare/session/YesCookieAuthFilterTest.java
This give access to all projects when using the YesCookieFilter authentication (https://github.com/ICIJ/datashare/issues/1167).
=> feat: dummy auth projects

datashare-app/src/main/resources/extensions.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.2.4
=> chore: bump version to 0.2.4

datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewer.java, datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
Related to [this issue](https://github.com/ICIJ/datashare/issues/1173)
=> feat: adds title titleNorm in ES document fields

datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java, datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java
This PR adds a new "dirname" column the batch search results CSV (see #1205)
* feat: add the new column and its header
* test: check the path and dirname are in the CSV
* refactor: review code style of the `getResultAsCsv`
=> feat: add dirname to batch search results

Makefile, datashare-app/src/main/java/org/icij/datashare/mode/LocalMode.java, datashare-app/src/main/java/org/icij/datashare/mode/ServerMode.java, datashare-app/src/main/java/org/icij/datashare/web/DocumentUserRecommendationResource.java, datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java, datashare-app/src/test/java/org/icij/datashare/web/DocumentUserRecommendationResourceTest.java, datashare-app/src/test/java/org/icij/datashare/web/DocumentUserRecommendationTest.java, datashare-db/src/main/java/org/icij/datashare/db/JooqRepository.java, datashare-db/src/main/resources/liquibase/changelog/changes/034-adds-creation-date-column-to-document-user-recommendation.yml, datashare-db/src/main/resources/liquibase/changelog/db.changelog.yml, datashare-db/src/test/java/org/icij/datashare/db/JooqRepositoryTest.java, pom.xml
This PR adds a new endpoint to get and filter `DocumentUserRecommendations` records (see #1228).
=> feat: get document user recommendations endpoint

datashare-app/src/main/java/org/icij/datashare/mode/ServerMode.java, datashare-app/src/main/java/org/icij/datashare/session/YesBasicAuthFilter.java, datashare-app/src/test/java/org/icij/datashare/session/YesBasicAuthFilterTest.java
Two issues:
* there was a misspelled and copy paste mistake in the test "protectedUrPrefix"
* the ApiKey filter was called before the auth filter, thus sending back a 401 that displayed the auth page
=> fix: the dummy auth filter was broken

datashare-app/src/main/resources/extensions.json, datashare-app/src/main/resources/plugins.json
- added the `datashare-plugin-neo4j-graph-widget` plugin with a backend dependency on `datashare-extension-neo4j`
- bumped `datashare-extension-neo4j` to `0.3.0`
=> chore: add support for `datashare-plugin-neo4j-graph-widget`

datashare-app/src/main/java/org/icij/datashare/CliApp.java, datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java, datashare-app/src/main/java/org/icij/datashare/tasks/BatchSearchRunner.java, datashare-app/src/main/java/org/icij/datashare/tasks/ResumeNlpTask.java, datashare-app/src/main/java/org/icij/datashare/web/BatchSearchResource.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerEncryptedIntTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerIntTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerIntTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/MockSearch.java, datashare-app/src/test/java/org/icij/datashare/tasks/TaskManagerRedisTest.java, datashare-app/src/test/java/org/icij/datashare/web/BatchSearchResourceTest.java, datashare-app/src/test/java/org/icij/datashare/web/NamedEntityResourceTest.java, datashare-db/src/main/java/org/icij/datashare/db/JooqBatchSearchRepository.java, datashare-db/src/main/resources/liquibase/changelog/changes/035-batch-search-rename-tag-column-to-query-body.yml, datashare-db/src/main/resources/liquibase/changelog/changes/035-batch-search-rename-tag-column-to-query-template.yml, datashare-db/src/main/resources/liquibase/changelog/db.changelog.yml, datashare-db/src/test/java/org/icij/datashare/db/JooqBatchSearchRepositoryTest.java, datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexer.java, datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchQueryBuilderSearcher.java, datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSearcher.java, datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchIndexerTest.java, pom.xml
PR related to [this issue](https://github.com/ICIJ/datashare/issues/1071) and [this one](https://github.com/ICIJ/datashare/issues/1248).
=> feat: adds tags in batch search

datashare-app/src/main/java/org/icij/datashare/WebApp.java, datashare-app/src/main/java/org/icij/datashare/com/bus/amqp/AmqpChannel.java, datashare-app/src/main/java/org/icij/datashare/com/bus/amqp/AmqpInterlocutor.java, datashare-app/src/main/java/org/icij/datashare/com/bus/amqp/Configuration.java, datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java, datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadLoop.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskManager.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerAmqp.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerMemory.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerRedis.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskSupplier.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskSupplierAmqp.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskView.java, datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java, datashare-app/src/test/java/org/icij/datashare/com/bus/amqp/AmqpTest.java, datashare-app/src/test/java/org/icij/datashare/com/bus/amqp/ConfigurationTest.java, datashare-app/src/test/java/org/icij/datashare/mode/CommonModeTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/TaskManagerAmqpTest.java, datashare-app/src/test/resources/datashare.properties, datashare-cli/src/main/java/org/icij/datashare/cli/QueueType.java
Instantiate AMQP task manager when `batchQueueType` option is set to AMQP.
Fix TaskManager Redis that has an unknown queueName.
=> Feat: amqp cli wirering

datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchConfiguration.java
Related to [this issue](https://github.com/ICIJ/datashare/issues/1282)
=> fix: process credentials and x-elastic in the same callback

datashare-app/src/main/resources/extensions.json, datashare-app/src/main/resources/plugins.json
- updated neo4j extension name
- add plugin name
=> chore: update neo4j extension name and add plugin name

datashare-app/src/main/java/org/icij/datashare/Main.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java, launchBack.sh
add a new option to set logback loglevel programmatically.
=> feat: add logLevel option

datashare-app/src/main/java/org/icij/datashare/tasks/EnqueueFromIndexTask.java, datashare-app/src/main/java/org/icij/datashare/tasks/ScanTask.java, datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java, datashare-app/src/test/java/org/icij/datashare/tasks/EnqueueFromIndexTaskTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/ScanIndexTaskTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/ScanTaskTest.java, datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java, pom.xml
=> Fix: scan queue name

datashare-app/src/main/java/org/icij/datashare/extract/RedisDocumentCollectionFactory.java, datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java, datashare-app/src/main/java/org/icij/datashare/web/ProjectResource.java, datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java, datashare-app/src/test/java/org/icij/datashare/extract/DocumentCollectionFactoryTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/ExtractNlpTaskIntTest.java, datashare-app/src/test/java/org/icij/datashare/web/ProjectResourceTest.java, datashare-app/src/test/java/org/icij/datashare/web/TaskResourceTest.java, datashare-index/src/main/java/org/icij/datashare/extract/DocumentCollectionFactory.java, datashare-index/src/main/java/org/icij/datashare/extract/MemoryDocumentCollectionFactory.java, datashare-index/src/test/java/org/icij/datashare/extract/MemoryDocumentCollectionFactoryTest.java, pom.xml
This PR use a unique hash from the PropertiesProvider to build a unique queueName.
=> feat: unique queue name

datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java, datashare-app/src/main/java/org/icij/datashare/mode/NerMode.java, pom.xml
=> fix: twice loading extensions

datashare-app/src/main/java/org/icij/datashare/web/TaskResource.java, datashare-app/src/test/java/org/icij/datashare/web/UserTaskResourceTest.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManager.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerMemory.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRunnerLoop.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskSupplier.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskSupplierAmqp.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskSupplierRedis.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskView.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/TaskError.java, datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerAmqpTest.java, datashare-tasks/src/test/java/org/icij/datashare/asynctasks/bus/amqp/TaskErrorTest.java
=> feat: implement a TaskError class instead of Throwable #1420

datashare-app/pom.xml, datashare-dist/pom.xml, pom.xml
=> chore: build use git plugin just for dist module

.circleci/config.yml
Related to [this issue](https://github.com/ICIJ/datashare/issues/1382)
=> ci: upload es json to github release

datashare-app/src/main/resources/extensions.json, datashare-app/src/main/resources/plugins.json
https://github.com/ICIJ/datashare-extension-neo4j/releases/tag/0.4.5
=> chore: bump neo4j pluging to `0.4.5`

datashare-api/src/main/java/org/icij/datashare/text/nlp/Pipeline.java
- added `SPACY` to the `Pipeline.Type` enum
=> feature: Add `Pipeline.Type.SPACY`

datashare-app/pom.xml, datashare-app/src/main/java/org/icij/datashare/ftm/FtmDocument.java, datashare-app/src/main/java/org/icij/datashare/mode/LocalMode.java, datashare-app/src/main/java/org/icij/datashare/mode/ServerMode.java, datashare-app/src/main/java/org/icij/datashare/web/FtmResource.java, datashare-app/src/test/java/org/icij/datashare/ftm/FtmDocumentTest.java, datashare-app/src/test/java/org/icij/datashare/web/FtmResourceTest.java, pom.xml
This PR is adding the [Follow the Money](https://followthemoney.tech/) implementation for a document.
It is a work in progress, a few properties are mapped into `FtmDocument`.
It is adding the dependency on [ftm.java](https://github.com/ICIJ/ftm.java)  and adding a new endpoint to get a document.
=> Feat: ftm integration

datashare-app/src/main/java/org/icij/datashare/tasks/BatchDownloadRunner.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchDownloadRunnerEncryptedIntTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/TaskWorkerIntTest.java
Related to #1600  and follows the issue #1492 
This PR aims to make Batch Downloads cancellable
=> feat: cancellable batch download

datashare-app/src/main/java/org/icij/datashare/mode/CommonMode.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerAmqp.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskManagerMemory.java, datashare-app/src/main/java/org/icij/datashare/tasks/TaskRepositoryRedis.java, datashare-app/src/test/java/org/icij/datashare/mode/CliModeWorkerAcceptanceTest.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java, datashare-cli/src/main/java/org/icij/datashare/cli/TaskRepositoryType.java, datashare-db/pom.xml, datashare-db/src/main/java/org/icij/datashare/db/JooqTaskRepository.java, datashare-db/src/main/java/org/icij/datashare/db/RepositoryFactoryImpl.java, datashare-db/src/main/resources/liquibase/changelog/changes/036-create_task.yml, datashare-db/src/main/resources/liquibase/changelog/db.changelog.yml, datashare-db/src/test/java/org/icij/datashare/db/DbSetupRule.java, datashare-db/src/test/java/org/icij/datashare/db/JooqTaskRepositoryTest.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/Task.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerAmqp.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerMemory.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskManagerRedis.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRepository.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRepositoryMemory.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskRepositoryRedis.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/TaskWorkerLoop.java, datashare-tasks/src/main/java/org/icij/datashare/asynctasks/bus/amqp/Event.java, datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerAmqpTest.java, datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerMemoryTest.java, datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagerRedisTest.java, datashare-tasks/src/test/java/org/icij/datashare/asynctasks/TaskManagersIntTest.java
This PR adds a `TaskRepository` object that contains the persistence of the `TaskManager`'s state.
see #1626
=> Feat: add task repository

datashare-index/src/test/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewerTest.java
- add test to verify language detection in a multi-OCR language setup
=> test(datashare-index): test multi language support

datashare-app/src/main/resources/extensions.json, datashare-app/src/main/resources/plugins.json
=> revert "feat: upgrade plugins/extensions to be compatible with the new design"

datashare-app/src/main/java/org/icij/datashare/tasks/BatchSearchRunner.java, datashare-app/src/test/java/org/icij/datashare/tasks/BatchSearchRunnerIntTest.java, datashare-app/src/test/java/org/icij/datashare/tasks/TaskManagerMemoryForBatchSearchTest.java
Related #1687 
This PR aims to synchronize the batch search status and the task status when the batch search fails.
=> feat: sync bs failure status and task status

datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCli.java, datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java, pom.xml
- added support for `TESS4J` ocr
=> feature: add support for `TESS4J` OCR

datashare-app/pom.xml, datashare-app/src/main/java/org/icij/datashare/web/DocumentResource.java, datashare-app/src/test/java/org/icij/datashare/web/DocumentResourceTest.java
The goal is to put a test to prove the cache is working.
We found some bugs. So we fixed them.
=> Test pages cache
